
// this file is mainly generated by an IA. So i havent check it all at this moment.

String generateMenu(){
  String res = "";

  res  += "<!DOCTYPE html><html><head><meta charset='UTF-8'>";
  res  += "<meta name='viewport' content='width=device-width, initial-scale=1.0'>";
  res  += "<style>";
  res  += "body { font-family: Arial, sans-serif; margin: 0; padding: 10px; background-color: #f2f2f2; }";
  res  += ".menu { display: flex; flex-wrap: wrap; justify-content: center; gap: 10px; margin-bottom: 20px; }";
  res  += ".menu a { background-color: #007BFF; color: #fff; padding: 10px 15px; text-decoration: none; border-radius: 4px; font-size: 16px; transition: background-color 0.3s ease; }";
  res  += ".menu a:hover { background-color: #0056b3; }";
  res  += "@media (max-width: 600px) { .menu a { flex: 1 1 100%; text-align: center; } }";
  res  += "</style></head><body>";
  res  += "<div class='menu'>";
  res  += "<a href='/'>Init</a>";
  res  += "<a href='ui'>Intervalometer</a>";
  res  += "<!--a href='ui_trampeo'>FotoTrampeo (next steps to do)</a-->";
  res  += "<a href='ui_status'>Status Camera</a>";
  res  += "</div>";
  res  += "<br/><br/>";

  return res;
}

String generateRootUI(){

  String res = "<h1>My Canon CCAI:</h1>";
  res  += generateMenu();

  res  += "<!DOCTYPE html><html><head><meta charset=\"UTF-8\">";
  res  += "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">";
  res  += "<style>";
  res  += "body { font-family: Arial, sans-serif; padding: 10px; margin: 0; background-color: #f2f2f2; color: #333; }";
  res  += "form { background-color: #fff; padding: 15px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); margin-bottom: 20px; }";
  res  += "table { width: 100%; border-collapse: collapse; }";
  res  += "td { padding: 8px; vertical-align: middle; }";
  res  += "input[type=\"text\"] { width: 100%; padding: 10px; margin: 5px 0; border: 1px solid #ccc; border-radius: 4px; }";
  res  += "input[type=\"submit\"] { width: 100%; padding: 10px; background-color: #28a745; border: none; border-radius: 4px; color: #fff; font-size: 16px; margin-top: 10px; }";
  res  += "input[type=\"submit\"]:hover { background-color: #218838; }";
  res  += "#status_div { background-color: #fff; padding: 10px; border-radius: 4px; margin-top: 20px; text-align: center; font-weight: bold; }";
  res  += "a { display: block; margin-top: 20px; text-align: center; color: #007BFF; text-decoration: none; font-size: 16px; }";
  res  += "a:hover { text-decoration: underline; }";
  res  += "@media (max-width: 600px) { td { display: block; width: 100%; } }";
  res  += "</style></head><body>";

  res  += "<form action=\"/connectCamera\" method=\"POST\">";
  res  += "<table>";
  res  += "<tr><td>IP:</td><td><input type=\"text\" name=\"ip\" placeholder=\"IP\" value=\"" + CAMERA_IP + "\"></td></tr>";
  res  += "<tr><td>PORT:</td><td><input type=\"text\" name=\"puerto\" placeholder=\"Puerto\" value=\"" + CAMERA_PORT + "\"></td></tr>";
  res  += "</table>";
  res  += "<input type=\"submit\" value=\"Conect-Test photo\">";
  res  += "</form>";

  res  += "<br>";

  res  += "<div id=\"status_div\">" + CAM_STATUS_CONNECTED + "</div>";
  res  += "<a href=\"" + CAMERA_IP + ":" + CAMERA_PORT + CAMERA_TEST_URL + "\" target=\"_blank\">Open URL Camera CANON - Connect with CAMERA</a>";

  res  += "</body></html>";

  return res;
}


String generateFotoTrampeoUI(){
  String res = "<h1>FotoTrampeo:</h1>";
  res  += generateMenu();
  res  += "</br></br></br></br>";
  res  += ""; 
  res  += "<div id=\"status_div\"></div>";
  res  += "";

  return res;
}

String generateStatusUI(){
  String res = "<h1>Status Camera (to do):</h1>";
  res  += generateMenu();
  res  += "</br></br></br></br>";
  res  += ""; 
  if (START_SHOOT == false){
        res  += "<div id=\"status_div\">STATUS: <b>STOPPED</b> </div>";
  } else {
         res  += "<div id=\"status_div\">STATUS:<b> SHOOTING</b> </div>";
  }
  res  += "<div id=\"status_div\">SHOOTSS:<b> "+ String(CURRENT_SHOOT) +"</b></div>";
  res  += "<div id=\"status_div\">TOTAL SHOOTS:<b> "+ String(CURRENT_SHOOT) +" </b></div>";
  res  += "<div id=\"status_div\"></div>";
  res  += "";

  return res;
}

String generateIntervalometerUI(){
  String res = "<h1>Intervalometer:</h1>";
  res  += generateMenu();

  res  += "<!DOCTYPE html><html><head><meta charset=\"UTF-8\">";
  res  += "<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">";
  res  += "<style>";
  res  += "body { font-family: Arial, sans-serif; padding: 10px; margin: 0; background-color: #f2f2f2; }";
  res  += "form { background-color: #fff; padding: 15px; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); }";
  res  += "table { width: 100%; border-collapse: collapse; }";
  res  += "td { padding: 8px; vertical-align: middle; }";
  res  += "input[type=\"text\"] { width: 100%; padding: 10px; margin: 5px 0; border: 1px solid #ccc; border-radius: 4px; }";
  res  += "input[type=\"checkbox\"] { margin-top: 10px; }";
  res  += "input[type=\"submit\"] { width: 100%; padding: 10px; background-color: #007BFF; border: none; border-radius: 4px; color: #fff; font-size: 16px; margin-top: 10px; }";
  res  += "@media (max-width: 600px) {";
  res  += "  td { display: block; width: 100%; }";
  res  += "}";
  res  += "</style></head><body>";
  res  += "<form action=\"/startIntervalometer\" method=\"POST\">";
  res  += "<table>";
  res  += "<tr><td>IP:</td><td><input type=\"text\" name=\"ip\" placeholder=\"IP\" value=\"" + CAMERA_IP + "\"></td></tr>";
  res  += "<tr><td>PORT:</td><td><input type=\"text\" name=\"puerto\" placeholder=\"Puerto\" value=\"" + CAMERA_PORT + "\"></td></tr>";
  res  += "<tr><td>Num. shoots:</td><td><input type=\"text\" name=\"numShoots\" placeholder=\"Num. shoots\" value=\"" + String(NUM_SHOOTS) + "\"></td></tr>";
  res  += "<tr><td>Interval secs:</td><td><input type=\"text\" name=\"intervalo\" placeholder=\"Intervalo\" value=\"" + String(FREQUENCY) + "\"></td></tr>";
  res  += "<tr><td>AF:</td><td><input type=\"checkbox\" name=\"af_shoot\" checked=\"checked\" value=\"true\"></td></tr>";
  res  += "<!--tr><td>Switchoff camera (not implemented yet):</td><td><input type=\"checkbox\" name=\"apagar\" value=\"false\"></td></tr-->";
  res  += "</table>";
  res  += "<input type=\"submit\" value=\"Start Intervalometer\">";
  res  += "</form>";


  res  += "</br></br></br></br>";
  res  += ""; 
  res  += "<div id=\"status_div\"></div>";
  res  += "";

  return res;
}